CREATE TABLE IF NOT EXISTS review_logs (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  word_id INTEGER NOT NULL REFERENCES words(id) ON DELETE CASCADE,
  rating INTEGER NOT NULL,
  is_correct INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_rl_user ON review_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_rl_created ON review_logs(created_at);

CREATE TABLE IF NOT EXISTS user_settings (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  reminder_hour INTEGER NOT NULL DEFAULT 20,
  daily_goal INTEGER NOT NULL DEFAULT 20,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE progress ADD COLUMN IF NOT EXISTS streak_correct INTEGER NOT NULL DEFAULT 0;
